ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.kilid.org/elasticsearch:${ELASTIC_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
